# This workflow will Run Unit Tests with Maven

name: Java CI with Maven

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Unit Tests with Maven
      working-directory: ./simple-spring-boot
      #run: mvn test
      run pwd